from django.urls import path

from .views import (
    index,
    login_view,
    productos,
    agregar_carrito,
    carrito,
    aumentar_carrito,
    disminuir_carrito,
    checkout,
    verificar_pago,
    productos_admin,
    crear_producto,
    editar_producto,
    eliminar_producto,
    mis_compras,
    compras_admin,
    cerrar_sesion,
    factura_pdf,
)

urlpatterns = [
    path("", index),
    path("login/", login_view, name="login"),
    path("productos/", productos, name="productos"),
    path("productos/admin/", productos_admin, name="productos_admin"),
    path("productos/crear/", crear_producto, name="crear_producto"),
    path("logout/", cerrar_sesion, name="cerrar_sesion"),
    path("productos/editar/<int:id>/", editar_producto, name="editar_producto"),
    path("productos/eliminar/<int:id>/", eliminar_producto, name="eliminar_producto"),
    path("carrito/agregar/<int:id>/", agregar_carrito, name="agregar_carrito"),
    path("carrito/", carrito, name="carrito"),
    path("carrito/aumentar/<int:id>/", aumentar_carrito, name="aumentar_carrito"),
    path("carrito/disminuir/<int:id>/", disminuir_carrito, name="disminuir_carrito"),
    path("checkout/", checkout, name="checkout"),
    path("verificar-pago/<int:id>/", verificar_pago, name="verificar_pago"),
    path("mis-compras/", mis_compras, name="mis_compras"),
    path("compras/", compras_admin, name="compras_admin"),
    path("transaccion/<int:id>/factura/", factura_pdf, name="factura_pdf"),
]